apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ .Values.app }}-deployment"
  labels:
    app: {{ .Values.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
        - image: "{{ .Values.image }}:{{ .Values.tag }}"
          imagePullPolicy: Always
          name: single
          ports:
            - containerPort: {{ .Values.port }}
          startupProbe:
            httpGet:
              port: {{ .Values.port }}
              path: {{ .Values.healthPath }}
          livenessProbe:
            httpGet:
              port: {{ .Values.port }}
              path: {{ .Values.healthPath }}
          readinessProbe:
            httpGet:
              port: {{ .Values.port }}
              path: {{ .Values.healthPath }}
status: {}